### ISSUE TITLE
Hey buddy 

### ISSUE THREAD

**Issue by djxcqtion** [TobiasPankner/Letterboxd-to-IMDb#1]
Thanks for the video btw. Very helpful. 

Trying to use this script. Everything perfect till the CMD pip install -r requirements.txt part where I get the error : 'pip' is not recognized as an internal or external command, operable program or batch file. Don't know what to do next. Would be grateful if you could help.

**Comment by djxcqtion** [comment]
Found out the issue :) .Sorry about this

**Comment by TobiasPankner** [comment]
No problem, if you have any more question feel free to ask 🙂
