### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by S1njack** [TobiasPankner/Letterboxd-to-IMDb#13]
File "letterboxd2imdb.py", line 93
    raise ValueError(f"Error rating on IMDb. Code: {resp.status_code}")
                                                                                                                   ^
SyntaxError: invalid syntax

**Comment by TobiasPankner** [comment]
Hi! What version of python are you using?

**Comment by S1njack** [comment]
Hi,
I am using python 3.13 on MacOS Sequioa

Cheers,
Jackson
