### ISSUE TITLE
Cookie file

### ISSUE THREAD

**Issue by dimaastakhov** [TobiasPankner/Letterboxd-to-IMDb#15]
Failed to read cookie.txt, have you created the file?

I don't know what to do. I've noticed that i can't copy value in Chrome, just select the text and copied it to the cookie.txt. And it's not looking the same as yours in youtube video.

Have you any ideas how i can solve the issue?

Thank you in advance

Best regards,
Dimitri

**Comment by TobiasPankner** [comment]
The file is not named correctly.
Make sure that the extension is not added twice (.json.json)

**Comment by dimaastakhov** [comment]
I'm sorry, but i think the name of the file is correct. Please, check the screenshot
![Untitled](https://github.com/user-attachments/assets/3a560f27-c762-43e5-8e1f-53672eac3625)

**Comment by TobiasPankner** [comment]
No, the file is named .txt.txt
Rename the file to just cookie and it will work

**Comment by dimaastakhov** [comment]
IT WORKED!!! THANK YOU SO MUCH!!
