### ISSUE TITLE
Module not found error

### ISSUE THREAD

**Issue by marioporfirio** [TobiasPankner/Letterboxd-to-IMDb#3]
![image](https://user-images.githubusercontent.com/21208925/191379439-73ceeade-6a72-459e-a7e1-9c420094985b.png)

No module named "requests"

**Comment by Tasamolic** [comment]
Same

**Comment by Tasamolic** [comment]
I had the same problem, so I typed "python -m install requests". That gave me another error concerning "tqdm", so I executed the same line of code, replacing "requests" with "tqdm". Then it worked.

Good luck!

**Comment by TobiasPankner** [comment]
Please follow the steps in the readme. There is one to install all dependencies.
