### ISSUE TITLE
can't transfer watchlist

### ISSUE THREAD

**Issue by 0101010101011** [TobiasPankner/Letterboxd-to-IMDb#4]
the ratings were transferred successfully but when I try to transfer the watch list I get the following error:

C:\Users\Admin\Desktop\Letterboxd-to-IMDb-master>py letterboxd2imdb.py -f .\ltr.zip -w
Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\Letterboxd-to-IMDb-master\letterboxd2imdb.py", line 6, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

Note: I renamed the letterboxd zip file to ltr.zip

**Comment by TobiasPankner** [comment]
Did you install the requirements with `pip install -r requirements.txt`?

**Comment by 0101010101011** [comment]
yes i did. Like i said i managed to transfer the ratings

**Comment by TobiasPankner** [comment]
Please try the command `pip install requests` before running the export.  
The error you are getting is because of a missing package.

**Comment by 0101010101011** [comment]
ok will try and report back once im at the computer. thank you!

**Comment by TobiasPankner** [comment]
Is this issue resolved now?

**Comment by 0101010101011** [comment]
> Please try the command `pip install requests` before running the export. The error you are getting is because of a missing package.

after running the command i get this:

C:\Users\Admin\Desktop\Letterboxd-to-IMDb-master>pip install requests
Requirement already satisfied: requests in c:\users\Admin\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (2.27.1)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\Admin\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from requests) (2.0.12)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\Admin\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from requests) (1.26.8)
Requirement already satisfied: idna<4,>=2.5 in c:\users\Admin\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from requests) (3.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\Admin\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from requests) (2021.10.8)

so the requirements were already present. I am still unable to export the watchlist

**Comment by TobiasPankner** [comment]
Very strange. One more thing you could try:  
`py -m pip install requests`

**Comment by TobiasPankner** [comment]
And also try running the export command with `python` instead of `py`

**Comment by TobiasPankner** [comment]
Closing this because it's most likely not an issue with the script
