### ISSUE TITLE
AttributeError: module 'argparse' has no attribute 'BooleanOptionalAction'

### ISSUE THREAD

**Issue by arboum7** [TobiasPankner/Letterboxd-to-IMDb#6]
Hello, have everything set up and on the latest release of python as of the posted date of this issue, along with the cookies.txt file and running the prereq script as followed in the README steps, but keep getting this AttributeError on the main function, so not sure how or what to do with this.
Below is the error I get everytime I try to run the script
```
Traceback (most recent call last):
  File "letterboxd2imdb.py", line 248, in <module>
    main()
  File "letterboxd2imdb.py", line 148, in main
    optional.add_argument("-c", dest="clean", action=argparse.BooleanOptionalAction,
AttributeError: module 'argparse' has no attribute 'BooleanOptionalAction'
```

**Comment by TobiasPankner** [comment]
Hi, did you install the dependencies?  
And please include the comand you are running which results in this error

**Comment by TobiasPankner** [comment]
Hi, you have to use a python version newer than 3.9. please update and try again

**Comment by TobiasPankner** [comment]
Will close this issue. Please add a comment if the issue persists.
Thanks

**Comment by arboum7** [comment]
Yea I solved it, basically the issue was that I had multiple versions installed on my machine (from 3.8 -> 3.11) and if you use the `python` command it will use the older version of python rather I had to use the `py` command instead to use the 3.11 version.
So maybe it’d be nicer/safer to change your README examples to use the `py` command instead.

**Comment by TobiasPankner** [comment]
I cannot really change the README to the the py command as this is different for other people and on other OSes.  
But glad you could solve it

**Comment by arboum7** [comment]
`py` command is also a global command for every OS like the `python` one and is actually the more recommended command to use for python scripts but up to you I guess. Thanks for the script thought, very clean and useful 👍
