### ISSUE TITLE
Error transferring watchlist (code 400)

### ISSUE THREAD

**Issue by galaxios** [TobiasPankner/Letterboxd-to-IMDb#7]
Transferring the ratings worked perfectly but then when it goes to transfer the watchlist it fails, it displays "Successfully added to watchlist: 0" and in the errors list shows the same error for all the titles "Error adding to IMDb watchlist. Code: 400"
I haven't managed to figure out what could be causing this

**Comment by TobiasPankner** [comment]
Maybe something changed on IMDbs side. I'll check it out in the next few days and get back to you

**Comment by galaxios** [comment]
Great, thanks for checking

**Comment by TobiasPankner** [comment]
I just tried it and it worked just fine. Can you send me the command you executed please?

**Comment by TobiasPankner** [comment]
And also try again with a fresh cookie, this might resolve the issue for you

**Comment by galaxios** [comment]
thanks again for taking the time to check. I guess something was wrong with my imdb watchlist because I got it to work after going into imdb and adding one movie to the watchlist manually, once I did that and tried running the script again it just worked
