### ISSUE TITLE
Does it work for max too?

### ISSUE THREAD

**Issue by pilotdanielm** [TobiasPankner/Letterboxd-to-IMDb#9]
I have the probllem that if I put 'pip install -r requirements.txt' in my Terminal on mac it says that it the command is not found. Dou you have abdy idea how to solve that

**Comment by TobiasPankner** [comment]
Hey, there is some problem with your python install. 
I am not on mac but look it up on the internet, I am sure this is a common problem.

**Comment by TobiasPankner** [comment]
Try running `python3 -m ensurepip`
